/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    links: Link;
    articles: Article;
    videos: Video;
    pages: Page;
    users: User;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    links: LinksSelect<false> | LinksSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'es') | ('en' | 'es')[];
  globals: {
    site: Site;
    header: Header;
    footer: Footer;
    socials: Social;
  };
  globalsSelect: {
    site: SiteSelect<false> | SiteSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    socials: SocialsSelect<false> | SocialsSelect<true>;
  };
  locale: 'en' | 'es';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Upload and manage images, videos, and other media files.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Manage website and external links.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "links".
 */
export interface Link {
  id: number;
  label: string;
  type?: ('reference' | 'custom' | 'static') | null;
  reference?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null);
  url?: string | null;
  staticPage?: ('/videos' | '/articles') | null;
  newTab?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Create and manage website pages with customizable layouts and SEO settings.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  layout?:
    | (
        | {
            /**
             * Optional title displayed above the accordion section. Set the context for the items below.
             */
            headerText?: string | null;
            items: {
              /**
               * The question displayed in the accordion header. Keep it clear and concise.
               */
              questionText: string;
              /**
               * Rich text answer revealed when the question is clicked. Can include formatting, links, and lists.
               */
              answerText: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'accordion';
          }
        | {
            /**
             * The main heading displayed above the button.
             */
            title?: string | null;
            /**
             * The label for the action button that reveals the group finder.
             */
            buttonText?: string | null;
            /**
             * Toggle to show or hide the "powered by alpha" branding tag.
             */
            showPoweredBy?: boolean | null;
            /**
             * Supporting text displayed above the Alpha group finder when it is expanded.
             */
            iframeHeader?: string | null;
            /**
             * The URL for the Alpha group finder experience.
             */
            iframeURL: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'alpha';
          }
        | {
            /**
             * The URL for the Alpha group finder experience.
             */
            iframeURL: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'alphaIframe';
          }
        | {
            /**
             * The quote text. Words will animate in one by one as user scrolls.
             */
            quote: string;
            /**
             * Words to highlight in the primary brand color. Enter words separated by commas to emphasize key phrases.
             */
            highlightedWords?: string | null;
            /**
             * Name of the person being quoted.
             */
            author?: string | null;
            /**
             * Choose "None" for no background, "Color" for solid gray, "Image" for a background image, or "Video" for animated video background.
             */
            backgroundType?: ('none' | 'color' | 'image' | 'video') | null;
            /**
             * Hex color for the section background when Background Type is "Color". Defaults to dark gray (#1a1a1a).
             */
            backgroundColor?: string | null;
            /**
             * Image behind the CTA section when Background Type is "Image".
             */
            backgroundImage?: (number | null) | Media;
            /**
             * Looping video behind the CTA section when Background Type is "Video".
             */
            backgroundVideo?: (number | null) | Media;
            desktopAspectRatio?: ('16:9' | '4:3') | null;
            mobileAspectRatio?: ('4:5' | '9:16') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'animatedQuote';
          }
        | {
            header?: string | null;
            articles: (number | Article)[];
            horizontalScrollPath?: boolean | null;
            showHeader?: boolean | null;
            showTitle?: boolean | null;
            showDescription?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'articleCarousel';
          }
        | {
            /**
             * Optional section title displayed above the carousel.
             */
            header?: string | null;
            cards: {
              /**
               * Choose between Image or Video for the card media. NOTE: Videos play with NO OVERLAY - content displays raw without any dimming or color treatment.
               */
              mediaType: 'image' | 'video';
              /**
               * The image for each card. Only used when Media Type is "Image".
               */
              cardImage?: (number | null) | Media;
              /**
               * The video for each card. Only used when Media Type is "Video". Loops automatically, plays muted. NOTE: No overlay is applied - video displays raw.
               */
              cardVideo?: (number | null) | Media;
              /**
               * Rich text content shown in the popup when a card is clicked.
               */
              modalContent: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              id?: string | null;
            }[];
            horizontalScrollPath?: ('off' | 'on') | null;
            /**
             * Aspect ratio for cards on desktop. Choose 16:9 (wide) or 4:3 (standard).
             */
            desktopAspectRatio: '4:5' | '9:16';
            /**
             * Aspect ratio for cards on mobile. Choose 4:5 (tall) or 9:16 (full tall).
             */
            mobileAspectRatio: '4:5' | '9:16';
            id?: string | null;
            blockName?: string | null;
            blockType: 'cardCarousel';
          }
        | {
            /**
             * The button text. Keep it short and action-oriented (e.g., "Start Now", "Learn More").
             */
            label: string;
            /**
             * Optional supporting text above the button to provide context. Can be hidden using Show Title toggle.
             */
            message?: string | null;
            /**
             * Toggle to show or hide the message text above the button.
             */
            showTitle?: ('show' | 'hide') | null;
            /**
             * Internal links to pages within the site, or external links to outside URLs.
             */
            link?: (number | null) | Link;
            /**
             * Choose "None" for no background, "Color" for solid gray, "Image" for a background image, or "Video" for animated video background.
             */
            backgroundType?: ('none' | 'color' | 'image' | 'video') | null;
            /**
             * Hex color for the section background when Background Type is "Color". Defaults to dark gray (#1a1a1a).
             */
            backgroundColor?: string | null;
            /**
             * Image behind the CTA section when Background Type is "Image".
             */
            backgroundImage?: (number | null) | Media;
            /**
             * Looping video behind the CTA section when Background Type is "Video".
             */
            backgroundVideo?: (number | null) | Media;
            desktopAspectRatio?: ('16:9' | '4:3') | null;
            mobileAspectRatio?: ('4:5' | '9:16') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            article: number | Article;
            showTitle?: boolean | null;
            showDescription?: boolean | null;
            showReadMore?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuredArticle';
          }
        | {
            /**
             * The image displayed on desktop/tablet screens. Will scale to full width of the content area.
             */
            desktopImage: number | Media;
            /**
             * The image displayed on mobile screens. Can be cropped differently to focus on key elements for smaller screens.
             */
            mobileImage: number | Media;
            caption?: ('on' | 'off') | null;
            /**
             * Optional text displayed below the image to provide context.
             */
            captionText?: string | null;
            desktopAspectRatio?: ('16:9' | '4:3') | null;
            mobileAspectRatio?: ('4:5' | '9:16') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuredImage';
          }
        | {
            video: number | Video;
            desktopAspectRatio?: ('16:9' | '4:3') | null;
            mobileAspectRatio?: ('4:5' | '9:16') | null;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuredVideo';
          }
        | {
            /**
             * Initial consent question (e.g., "Did anything here shift how you think about Jesus?").
             */
            questionText?: string | null;
            /**
             * Text for positive consent button. Default: "Yes".
             */
            yesButtonLabel?: string | null;
            /**
             * Text for negative consent button. Default: "No".
             */
            noButtonLabel?: string | null;
            /**
             * Title shown when user clicks Yes (e.g., "We're so glad...").
             */
            yesFormTitle?: string | null;
            /**
             * Title shown when user clicks No (e.g., "We'd love to hear more...").
             */
            noFormTitle?: string | null;
            /**
             * First Name (optional), Last Name (optional), Email (required), Message textarea (required). All use floating labels with yellow borders.
             */
            formFields?: {
              /**
               * Include First Name field (optional).
               */
              firstName?: boolean | null;
              /**
               * Include Last Name field (optional).
               */
              lastName?: boolean | null;
              /**
               * Include Email field (required).
               */
              email?: boolean | null;
              /**
               * Include Message textarea (required).
               */
              message?: boolean | null;
            };
            /**
             * Required acknowledgment checkbox with link to privacy policy. Must be checked to submit.
             */
            privacyCheckbox: boolean;
            /**
             * Optional checkbox allowing user to consent to future contact.
             */
            contactCheckbox?: boolean | null;
            /**
             * URL to your privacy policy page.
             */
            privacyLink?: (number | null) | Link;
            /**
             * Returns to consent question. Default: "Back".
             */
            backButton?: string | null;
            /**
             * Submits the form. Default: "Submit".
             */
            submitButton?: string | null;
            /**
             * Title displayed after successful form submission. Default: "Thank You".
             */
            successTitle?: string | null;
            /**
             * Message displayed after successful form submission.
             */
            successDescription?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'feedback';
          }
        | {
            /**
             * Rich editor supporting headings, paragraphs, bold, italic, links, and lists.
             */
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            backgroundType?: ('none' | 'color' | 'image' | 'video') | null;
            /**
             * Upload a looping video file (MP4 recommended). Only shown when Background is set to 'Video'.
             */
            backgroundVideo?: (number | null) | Media;
            /**
             * Upload a full background image.
             */
            backgroundImage?: (number | null) | Media;
            /**
             * Hex color value (e.g. #1A1A1A)
             */
            backgroundColor?: string | null;
            /**
             * Hex color value (e.g. #B0B0B0)
             */
            textColor?: string | null;
            textAlignment?: ('left' | 'centered') | null;
            verticalAlignment?: ('top' | 'center') | null;
            multiLinesOfText?: ('off' | 'on') | null;
            desktopAspectRatio?: ('16:9' | '4:3') | null;
            mobileAspectRatio?: ('4:5' | '9:16') | null;
            textAnimation?:
              | (
                  | 'flashLineByLine'
                  | 'flashLineByLineNoFade'
                  | 'stackLineOnLine'
                  | 'appearWordByWord'
                  | 'appearParagraphByParagraph'
                  | 'none'
                )
              | null;
            /**
             * Words to highlight in the primary brand color. Enter words separated by commas to emphasize key phrases.
             */
            highlightedWords?: string | null;
            /**
             * Show a progress bar for this section.
             */
            progressBar?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'justText';
          }
        | {
            /**
             * The heading text to display. Supports branded color highlighting via the Branded Words field.
             */
            titleText: string;
            /**
             * Choose H1 through H3 to set the semantic heading level and size. H1 is largest, H3 is smallest.
             */
            headingLevel: 'h1' | 'h2' | 'h3';
            /**
             * Select Oswald (sans-serif, bold) or Merriweather (serif, elegant) for the title text.
             */
            fontFamily: 'oswald' | 'merriweather';
            textAlignment?: ('left' | 'center' | 'right') | null;
            /**
             * Hex color value (e.g. #FFFFFF)
             */
            textColor?: string | null;
            /**
             * Words to highlight in the primary brand color. Enter words separated by commas to emphasize key phrases.
             */
            highlightedWords?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'justTitle';
          }
        | {
            /**
             * Array of intro lines displayed before the play button. Each line appears on its own row.
             */
            introLines?:
              | {
                  line?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Secondary instruction (e.g., 'Press play to begin').
             */
            subText?: string | null;
            showSubText?: ('show' | 'hide') | null;
            /**
             * Array of scene objects. Each scene has: Title (rich text with yellow highlighting), Quote (italic text), and Body (rich text with line breaks). Use HTML spans for yellow: <span style="color: #feda00">word</span>
             */
            scenes: {
              /**
               * Rich text title with branded color highlighting. Use HTML spans for yellow: <span style="color: #feda00">word</span>
               */
              title?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              /**
               * Italic text displayed in the scene.
               */
              quote?: string | null;
              /**
               * Rich text body content with line breaks.
               */
              body?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              id?: string | null;
            }[];
            /**
             * Total timer length in seconds. Default is 60 seconds. Time is distributed across all scenes.
             */
            duration?: number | null;
            /**
             * Controls the pace of word-by-word animation. Default: 1.0. Range: 0.1 (slower) to 3.0 (faster). Higher values make words appear faster.
             */
            animationSpeed?: number | null;
            /**
             * Ambient background for the experience. Can be image or looping video. Video plays silently.
             */
            backgroundType?: ('image' | 'video') | null;
            backgroundImage?: (number | null) | Media;
            backgroundVideo?: (number | null) | Media;
            desktopAspectRatio?: '16:9' | null;
            mobileAspectRatio?: '9:16' | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pauseExperience';
          }
        | {
            /**
             * Rich text content. Supports branded color highlighting for emphasis.
             */
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            /**
             * Body (larger, default) or Small Text for secondary content.
             */
            textSize?: ('body' | 'smallText') | null;
            textAlignment?: ('left' | 'center' | 'right') | null;
            /**
             * Hex color value (e.g. #d1d5db)
             */
            textColor?: string | null;
            /**
             * Words to highlight in the primary brand color. Enter words separated by commas to emphasize key phrases.
             */
            highlightedWords?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'paragraphText';
          }
        | {
            /**
             * Motivational text encouraging users to share. Example: "Think about someone right now, who might need this journey, and share it".
             */
            title?: string | null;
            showTitle?: ('show' | 'hide') | null;
            /**
             * The URL to be shared. Defaults to current page URL if not specified.
             */
            shareURL?: string | null;
            /**
             * Default message text included when sharing via native share sheet.
             */
            shareText?: string | null;
            /**
             * Single button that opens the native device share sheet (Web Share API). Falls back to copy link on unsupported browsers.
             */
            shareButton: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'socialShare';
          }
        | {
            media: 'video' | 'image';
            /**
             * Full-screen video for the takeover experience. Desktop uses 16:9 (horizontal), Mobile uses 9:16 (vertical).
             */
            video?: (number | null) | Media;
            /**
             * Background image for the takeover. Desktop uses 16:9 (horizontal), Mobile uses 9:16 (vertical).
             */
            image?: (number | null) | Media;
            /**
             * Button to replay the video with audio enabled.
             */
            replayWithAudio?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'takeOver';
          }
        | {
            /**
             * Optional section title displayed above the carousel.
             */
            header?: string | null;
            slides: {
              /**
               * The title for each text slide. Can be hidden per slide using Show Title toggle.
               */
              slideTitle?: string | null;
              /**
               * Toggle to show or hide the title for this specific slide.
               */
              showTitle?: ('on' | 'off') | null;
              /**
               * Rich text content for each slide. Supports formatting, links, and lists.
               */
              slideBody: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              /**
               * Choose "None" for transparent, "Color" for solid gray, "Image" for a background image, or "Video" for animated video background. Each slide can have a different background.
               */
              backgroundType?: ('none' | 'color' | 'image' | 'video') | null;
              /**
               * Hex color for the slide background when Background Type is "Color". Defaults to dark gray (#1a1a1a).
               */
              backgroundColor?: string | null;
              /**
               * Image shown behind slide content when Background Type is "Image".
               */
              backgroundImage?: (number | null) | Media;
              /**
               * Looping video shown behind slide content when Background Type is "Video".
               */
              backgroundVideo?: (number | null) | Media;
              id?: string | null;
            }[];
            horizontalScrollPath?: ('off' | 'on') | null;
            /**
             * Hex color for slide titles. Defaults to white (#ffffff).
             */
            titleColor?: string | null;
            /**
             * Hex color for slide body text. Defaults to gray (#9ca3af).
             */
            subtextColor?: string | null;
            /**
             * Select 4:5 (tall) or 9:16 (full tall) for the slide aspect ratio on desktop screens.
             */
            desktopAspectRatio?: ('4:5' | '9:16') | null;
            /**
             * Select 4:5 (tall) or 9:16 (full tall) for the slide aspect ratio on mobile screens.
             */
            mobileAspectRatio?: ('4:5' | '9:16') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textCarousel';
          }
        | {
            header?: string | null;
            videos: (number | Video)[];
            desktopAspectRatio?: ('9:16' | '16:9') | null;
            mobileAspectRatio?: ('9:16' | '16:9') | null;
            horizontalScrollPath?: boolean | null;
            showHeader?: boolean | null;
            showVideoTitles?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'videoCarousel';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Manage articles with content, images, and reference links.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  image?: (number | null) | Media;
  referenceLink?: (number | null) | Link;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage video embeds with thumbnails and metadata.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  title?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  platform: 'youtube';
  orientation: 'horizontal' | 'vertical';
  /**
   * The unique identifier from the video URL. For YouTube: the part after "v=" in the URL.
   */
  videoId: string;
  thumbnailType?: ('image' | 'video') | null;
  thumbnail?: (number | null) | Media;
  videoThumbnail?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage user accounts and authentication credentials.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor' | 'user';
  totpSecret?: string | null;
  hasTotp?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'links';
        value: number | Link;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "links_select".
 */
export interface LinksSelect<T extends boolean = true> {
  label?: T;
  type?: T;
  reference?: T;
  url?: T;
  staticPage?: T;
  newTab?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  image?: T;
  referenceLink?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  platform?: T;
  orientation?: T;
  videoId?: T;
  thumbnailType?: T;
  thumbnail?: T;
  videoThumbnail?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  layout?:
    | T
    | {
        accordion?:
          | T
          | {
              headerText?: T;
              items?:
                | T
                | {
                    questionText?: T;
                    answerText?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        alpha?:
          | T
          | {
              title?: T;
              buttonText?: T;
              showPoweredBy?: T;
              iframeHeader?: T;
              iframeURL?: T;
              id?: T;
              blockName?: T;
            };
        alphaIframe?:
          | T
          | {
              iframeURL?: T;
              id?: T;
              blockName?: T;
            };
        animatedQuote?:
          | T
          | {
              quote?: T;
              highlightedWords?: T;
              author?: T;
              backgroundType?: T;
              backgroundColor?: T;
              backgroundImage?: T;
              backgroundVideo?: T;
              desktopAspectRatio?: T;
              mobileAspectRatio?: T;
              id?: T;
              blockName?: T;
            };
        articleCarousel?:
          | T
          | {
              header?: T;
              articles?: T;
              horizontalScrollPath?: T;
              showHeader?: T;
              showTitle?: T;
              showDescription?: T;
              id?: T;
              blockName?: T;
            };
        cardCarousel?:
          | T
          | {
              header?: T;
              cards?:
                | T
                | {
                    mediaType?: T;
                    cardImage?: T;
                    cardVideo?: T;
                    modalContent?: T;
                    id?: T;
                  };
              horizontalScrollPath?: T;
              desktopAspectRatio?: T;
              mobileAspectRatio?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              label?: T;
              message?: T;
              showTitle?: T;
              link?: T;
              backgroundType?: T;
              backgroundColor?: T;
              backgroundImage?: T;
              backgroundVideo?: T;
              desktopAspectRatio?: T;
              mobileAspectRatio?: T;
              id?: T;
              blockName?: T;
            };
        featuredArticle?:
          | T
          | {
              article?: T;
              showTitle?: T;
              showDescription?: T;
              showReadMore?: T;
              id?: T;
              blockName?: T;
            };
        featuredImage?:
          | T
          | {
              desktopImage?: T;
              mobileImage?: T;
              caption?: T;
              captionText?: T;
              desktopAspectRatio?: T;
              mobileAspectRatio?: T;
              id?: T;
              blockName?: T;
            };
        featuredVideo?:
          | T
          | {
              video?: T;
              desktopAspectRatio?: T;
              mobileAspectRatio?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        feedback?:
          | T
          | {
              questionText?: T;
              yesButtonLabel?: T;
              noButtonLabel?: T;
              yesFormTitle?: T;
              noFormTitle?: T;
              formFields?:
                | T
                | {
                    firstName?: T;
                    lastName?: T;
                    email?: T;
                    message?: T;
                  };
              privacyCheckbox?: T;
              contactCheckbox?: T;
              privacyLink?: T;
              backButton?: T;
              submitButton?: T;
              successTitle?: T;
              successDescription?: T;
              id?: T;
              blockName?: T;
            };
        justText?:
          | T
          | {
              content?: T;
              backgroundType?: T;
              backgroundVideo?: T;
              backgroundImage?: T;
              backgroundColor?: T;
              textColor?: T;
              textAlignment?: T;
              verticalAlignment?: T;
              multiLinesOfText?: T;
              desktopAspectRatio?: T;
              mobileAspectRatio?: T;
              textAnimation?: T;
              highlightedWords?: T;
              progressBar?: T;
              id?: T;
              blockName?: T;
            };
        justTitle?:
          | T
          | {
              titleText?: T;
              headingLevel?: T;
              fontFamily?: T;
              textAlignment?: T;
              textColor?: T;
              highlightedWords?: T;
              id?: T;
              blockName?: T;
            };
        pauseExperience?:
          | T
          | {
              introLines?:
                | T
                | {
                    line?: T;
                    id?: T;
                  };
              subText?: T;
              showSubText?: T;
              scenes?:
                | T
                | {
                    title?: T;
                    quote?: T;
                    body?: T;
                    id?: T;
                  };
              duration?: T;
              animationSpeed?: T;
              backgroundType?: T;
              backgroundImage?: T;
              backgroundVideo?: T;
              desktopAspectRatio?: T;
              mobileAspectRatio?: T;
              id?: T;
              blockName?: T;
            };
        paragraphText?:
          | T
          | {
              content?: T;
              textSize?: T;
              textAlignment?: T;
              textColor?: T;
              highlightedWords?: T;
              id?: T;
              blockName?: T;
            };
        socialShare?:
          | T
          | {
              title?: T;
              showTitle?: T;
              shareURL?: T;
              shareText?: T;
              shareButton?: T;
              id?: T;
              blockName?: T;
            };
        takeOver?:
          | T
          | {
              media?: T;
              video?: T;
              image?: T;
              replayWithAudio?: T;
              id?: T;
              blockName?: T;
            };
        textCarousel?:
          | T
          | {
              header?: T;
              slides?:
                | T
                | {
                    slideTitle?: T;
                    showTitle?: T;
                    slideBody?: T;
                    backgroundType?: T;
                    backgroundColor?: T;
                    backgroundImage?: T;
                    backgroundVideo?: T;
                    id?: T;
                  };
              horizontalScrollPath?: T;
              titleColor?: T;
              subtextColor?: T;
              desktopAspectRatio?: T;
              mobileAspectRatio?: T;
              id?: T;
              blockName?: T;
            };
        videoCarousel?:
          | T
          | {
              header?: T;
              videos?: T;
              desktopAspectRatio?: T;
              mobileAspectRatio?: T;
              horizontalScrollPath?: T;
              showHeader?: T;
              showVideoTitles?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  totpSecret?: T;
  hasTotp?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Configure global site settings including branding, SEO defaults, and maintenance mode.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: number;
  title: string;
  logo: number | Media;
  favicon: number | Media;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * Main brand colors used across the site.
   */
  primaryColors: {
    /**
     * #FEDA00
     */
    primaryGold: string;
  };
  /**
   * Colors used for typography and text elements.
   */
  textColors: {
    /**
     * #FFFFFF
     */
    white: string;
    /**
     * #86888A
     */
    gray: string;
    /**
     * #FEDA00
     */
    primaryGold: string;
  };
  /**
   * Background colors for card and box elements.
   */
  boxBackground: {
    /**
     * #444546
     */
    boxBgGray: string;
  };
  /**
   * Neutral palette for backgrounds, surfaces, and borders.
   */
  neutrals: {
    /**
     * #0A0A0A
     */
    background: string;
    /**
     * #1A1A1A
     */
    surface: string;
    /**
     * #252525
     */
    border: string;
    /**
     * #FFFFFF
     */
    white: string;
    /**
     * #B0B0B0
     */
    gray: string;
  };
  maintenanceMode?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage the site header navigation links.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: number | Link;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage the site footer including copyright text and navigation links.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  copyrightText: string;
  navItems?:
    | {
        link: number | Link;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configure social media links and icons displayed across the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "socials".
 */
export interface Social {
  id: number;
  links?:
    | {
        platform: 'Facebook' | 'X' | 'YouTube' | 'Instagram' | 'TikTok' | 'LinkedIn' | 'Telegram';
        url: string;
        icon: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  title?: T;
  logo?: T;
  favicon?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  primaryColors?:
    | T
    | {
        primaryGold?: T;
      };
  textColors?:
    | T
    | {
        white?: T;
        gray?: T;
        primaryGold?: T;
      };
  boxBackground?:
    | T
    | {
        boxBgGray?: T;
      };
  neutrals?:
    | T
    | {
        background?: T;
        surface?: T;
        border?: T;
        white?: T;
        gray?: T;
      };
  maintenanceMode?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  copyrightText?: T;
  navItems?:
    | T
    | {
        link?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "socials_select".
 */
export interface SocialsSelect<T extends boolean = true> {
  links?:
    | T
    | {
        platform?: T;
        url?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}